### Obtener país por id
GET http://localhost:8081/paises/0
Content-Type: application/json

{
}

### Obtener todos los países registrados
GET http://localhost:8081/paises
Content-Type: application/json

{
}

### Obtener todas las publicaciones de un país
GET http://localhost:8081/paises/0/publicaciones
Content-Type: application/json

{
}